### ISSUE TITLE
Disable RBF (Replace by fee) for refund transaction

### ISSUE THREAD

**Issue by chronark** [chronark/swapchain#147]
Currently it's possible to replace this manually but it probably shouldn't be.

**Comment by webersni** [comment]
Refunding transactions might be replaced by transactions with higher fees using the so called RBF (Replace by fee) mechanism. This should be disabled if possible.

**Comment by webersni** [comment]
I've checked this issue. It's actually rather a feature than a bug. It offers a last chance to run the ACCS.
