### ISSUE TITLE
Optimize timeouts in accs

### ISSUE THREAD

**Issue by chronark** [chronark/swapchain#148]
Various custom async loops have magic timeouts that we can optimize.

**Comment by webersni** [comment]
We should also consider security aspects for this. The parties should wait at least until the Bitcoin transaction is confirmed one time.

**Comment by webersni** [comment]
Magic timeouts are fixed. We now use a config value "checkAPIInterval" which is currently set to 4 seconds.

**Comment by webersni** [comment]
Second issue is also fixed. We now wait until the Bitcoin transaction is confirmed to be in a block.
