### ISSUE TITLE
Fix documentation

### ISSUE THREAD

**Issue by chronark** [chronark/swapchain#165]
Currently we aren't even building new docs.

**Comment by JuliaSte** [comment]
**product documentation:** 

As soon as the UI is in the final stage: 

- screenshots from the different forms and adding explanation to the different buttons to explain the functionality 
- record screencast as soon as all the functionalities are implemented so the user can get an idea how the websites works

**Comment by madsjordt** [comment]
From Spyros' message in Teams I understood that he and Katha are actually creating the video? I will ask him.

**Comment by madsjordt** [comment]
@chronark @JuliaSte seems like everything is fixed. Can I close this issue?

**Comment by JuliaSte** [comment]
yes, I think so. Unless @chronark there's anything from your side why it needs to remain open.
