### ISSUE TITLE
Remove dead links in UI

### ISSUE THREAD

**Issue by madsjordt** [chronark/swapchain#200]

**Comment by madsjordt** [comment]
Just summarizing all buttons / links from our nelify app:

Trade: Start trading, Propose / Accept
CLI: https://github.com/chronark/swapchain#cli
Orderbook: Dummy Orderbook
Github icon: https://github.com/chronark/swapchain
Learn more: https://github.com/chronark/swapchain

TO BE DONE:
Documentation: Page Not Found

**Comment by webersni** [comment]
Fixed.
