### ISSUE TITLE
Add Bitshares account name to data to be passed to the partner

### ISSUE THREAD

**Issue by JuliaSte** [chronark/swapchain#202]
Just out of completion reasons we could add the bitshares account name as a third information that needs to be passed to the partner to fill out the counterparty data. 
Plus I would switch the order from first presenting the public key and then the hash as the user might also insert it in that order. 
But we can check with the others what they think as this is just a really minor thing.

**Comment by webersni** [comment]
Technically we could do that, but a Bitshares account is not changed often and the user should therefore know it by heart. This is also the reason why the Bitshares community decided to introduce accounts.
